INSERT  INTO product (name) VALUES ('Asus PadFone');
INSERT  INTO product (name) VALUES ('Asus PadFone ');
INSERT  INTO product (name) VALUES ('Asus PadFone 2 ');
INSERT  INTO product (name) VALUES ('Asus PadFone Infinity ');
INSERT  INTO product (name) VALUES ('Asus PadFone Infinity 2 ');
INSERT  INTO product (name) VALUES ('Asus PadFone mini ');
INSERT  INTO product (name) VALUES ('Asus PadFone E ');
INSERT  INTO product (name) VALUES ('Asus PadFone Infinity Lite ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 5 (2014) ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 4 (2014) ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 6 (2014) ');
INSERT  INTO product (name) VALUES ('Asus PadFone S/X ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 4.5 (2014) ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 5 (2014) ');
INSERT  INTO product (name) VALUES ('Asus PadFone X mini ');
INSERT  INTO product (name) VALUES ('Asus Pegasus (X002) ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 5 (2015) ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 2 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 3 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 4 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone Max Plus M1 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone Max M1 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone Max Pro M1 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 5 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone Live L1 ');
INSERT  INTO product (name) VALUES ('Asus ROG Phone ');
INSERT  INTO product (name) VALUES ('Asus ZenFone Lite L1 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone Max M2 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone Max Pro M2 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone Max Shot ');
INSERT  INTO product (name) VALUES ('Asus ZenFone Max Plus M2 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone Live L2 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 6 ');
INSERT  INTO product (name) VALUES ('Asus ROG Phone II ');
INSERT  INTO product (name) VALUES ('Asus ROG Phone 3 ');
INSERT  INTO product (name) VALUES ('Asus ZenFone 7 ');
INSERT  INTO product (name) VALUES ('Asus ROG Phone 5 ');


