version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Supertajneheslo1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: shop
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
